### ISSUE TITLE
Regular BetaNet Bootstrap file with blockchain is missing

### ISSUE THREAD

**Issue by Bambarello** [sero-cash/go-sero#4]
Please consider creating cronjob on some of bootstrapping nodes, archive and publish fresh bootstrap file on some hosting, update the new node running instructions and consider adding the bootstrap download-extraction for new node/wallet setup. Thanks!

**Comment by Bambarello** [comment]
no more relevant

**Comment by jedicidal** [comment]
> no more relevant

why?
