### ISSUE TITLE
Error during node sync (gero version 0.7.0 beta r7

### ISSUE THREAD

**Issue by Bambarello** [sero-cash/go-sero#5]
Here is the errors i've detected during sync process:

`ERROR[04-16|18:10:04.773] validateTx error :                       hash=0x99c9449d9d10f9c4dcbcefcefdd0446fd1e4f474a2bc92f88fc21980f5187608 recover="missing trie node 29545969bfecf5ada4ec131621f094c710
740454db5b29fcf955aad03217af36 (path 0603)"
goroutine 210779 [running]:
runtime/debug.Stack(0x1260b22, 0x13, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/sero-cash/go-sero/core.(*TxPool).validateTx.func1(0xc084b3cf00, 0xc00ff62ae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:445 +0x1ad
panic(0x112ec60, 0xc05d9ce900)
        /usr/local/go/src/runtime/panic.go:513 +0x1c7
github.com/sero-cash/go-sero/zero/utils.(*HSet).Has(0xc052bca5c8, 0x1b0fe80, 0xc0332bbc80, 0xc048e9efe0, 0xc00ff61fc8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/utils/hset.go:61 +0x200
github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1.(*Data).HasIn(0xc052bca5a0, 0x1b0fe80, 0xc0332bbc80, 0xc048e9efe0, 0xc048e9efc0)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1/data_state.go:33 +0x56
github.com/sero-cash/go-sero/zero/txs/zstate/txstate.(*State).HasIn(0xc00bd73008, 0xc048e9efe0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/state.go:137 +0x9b
github.com/sero-cash/go-sero/zero/txs/verify.Verify_state1(0xc021bd74a0, 0xc00bd72ff0, 0x11408e0, 0xc0556f02f8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:184 +0x8a9
github.com/sero-cash/go-sero/zero/txs/verify.Verify(0xc021bd74a0, 0xc00bd72ff0, 0xc084b3cf00, 0xc00ff62ae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:44 +0x3c
github.com/sero-cash/go-sero/core.(*TxPool).validateTx(0xc000003380, 0xc084b3cf00, 0x6f44d0fdceefbc00, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:460 +0x108
github.com/sero-cash/go-sero/core.(*TxPool).add(0xc000003380, 0xc084b3cf00, 0x0, 0xc02ae4e790, 0x1, 0x1)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:497 +0xd4
github.com/sero-cash/go-sero/core.(*TxPool).addTxsLocked(0xc000003380, 0xc03e369200, 0x1, 0x4, 0x0, 0xc00ff63148, 0x2, 0x2)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:599 +0xc4
github.com/sero-cash/go-sero/core.(*TxPool).addTxs(0xc000003380, 0xc03e369200, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:589 +0xb6
github.com/sero-cash/go-sero/core.(*TxPool).AddRemotes(0xc000003380, 0xc03e369200, 0x1, 0x4, 0x87618f58019c28f, 0xee2f87acef5, 0x2166b80)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:567 +0x172
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handleMsg(0xc000544300, 0xc07c9cd980, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:623 +0x48a
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handle(0xc000544300, 0xc07c9cd980, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:285 +0x6f2
github.com/sero-cash/go-sero/sero.NewProtocolManager.func1(0xc066f90f60, 0x1b09100, 0xc035196cb0, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:137 +0x1bf
github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols.func1(0xc035196cb0, 0xc066f90f60, 0x1b09100, 0xc035196cb0)
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:353 +0x6d
created by github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:352 +0x202
ERROR[04-16|18:10:04.794] validateTx error :                       hash=0x99c9449d9d10f9c4dcbcefcefdd0446fd1e4f474a2bc92f88fc21980f5187608 recover="missing trie node 29545969bfecf5ada4ec131621f094c710
740454db5b29fcf955aad03217af36 (path 0603)"
goroutine 211077 [running]:
runtime/debug.Stack(0x1260b22, 0x13, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/sero-cash/go-sero/core.(*TxPool).validateTx.func1(0xc058d68dc0, 0xc0485baae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:445 +0x1ad
panic(0x112ec60, 0xc05d9cea00)
        /usr/local/go/src/runtime/panic.go:513 +0x1c7
github.com/sero-cash/go-sero/zero/utils.(*HSet).Has(0xc052bca5c8, 0x1b0fe80, 0xc0332bbc80, 0xc05be42920, 0xc0485b9fc8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/utils/hset.go:61 +0x200
github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1.(*Data).HasIn(0xc052bca5a0, 0x1b0fe80, 0xc0332bbc80, 0xc05be42920, 0xc05be42900)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1/data_state.go:33 +0x56
github.com/sero-cash/go-sero/zero/txs/zstate/txstate.(*State).HasIn(0xc00bd73008, 0xc05be42920, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/state.go:137 +0x9b
github.com/sero-cash/go-sero/zero/txs/verify.Verify_state1(0xc01e4470e0, 0xc00bd72ff0, 0x11408e0, 0xc05b696320)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:184 +0x8a9
github.com/sero-cash/go-sero/zero/txs/verify.Verify(0xc01e4470e0, 0xc00bd72ff0, 0xc058d68dc0, 0xc0485baae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:44 +0x3c
github.com/sero-cash/go-sero/core.(*TxPool).validateTx(0xc000003380, 0xc058d68dc0, 0x6f44d0fdceefbc00, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:460 +0x108
github.com/sero-cash/go-sero/core.(*TxPool).add(0xc000003380, 0xc058d68dc0, 0x0, 0xc02ae4e890, 0x1, 0x1)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:497 +0xd4
github.com/sero-cash/go-sero/core.(*TxPool).addTxsLocked(0xc000003380, 0xc026e55940, 0x1, 0x4, 0x0, 0xc0485bb148, 0x2, 0x2)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:599 +0xc4
github.com/sero-cash/go-sero/core.(*TxPool).addTxs(0xc000003380, 0xc026e55940, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:589 +0xb6
github.com/sero-cash/go-sero/core.(*TxPool).AddRemotes(0xc000003380, 0xc026e55940, 0x1, 0x4, 0x87618f58019c28f, 0xee2f9507195, 0x2166b80)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:567 +0x172
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handleMsg(0xc000544300, 0xc06916c0c0, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:623 +0x48a
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handle(0xc000544300, 0xc06916c0c0, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:285 +0x6f2
github.com/sero-cash/go-sero/sero.NewProtocolManager.func1(0xc03386a2a0, 0x1b09100, 0xc008553490, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:137 +0x1bf
github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols.func1(0xc008553490, 0xc03386a2a0, 0x1b09100, 0xc008553490)
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:353 +0x6d
created by github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:352 +0x202
ERROR[04-16|18:10:05.105] validateTx error :                       hash=0x6d7d7fcecd8918922be9f5feaff6b88cf3260e01f7e30832706eb48c43009d7d recover="missing trie node d1f1ff3381fcf7253b0f49f303116b01e7
e7fc936dc9b3a8deb346268a6def2a (path 0c07)"
goroutine 20632 [running]:
runtime/debug.Stack(0x1260b22, 0x13, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/sero-cash/go-sero/core.(*TxPool).validateTx.func1(0xc06e194c30, 0xc008e10ae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:445 +0x1ad
panic(0x112ec60, 0xc05d9ceb00)
        /usr/local/go/src/runtime/panic.go:513 +0x1c7
github.com/sero-cash/go-sero/zero/utils.(*HSet).Has(0xc052bca5c8, 0x1b0fe80, 0xc0332bbc80, 0xc05fdccea0, 0xc02af67fc8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/utils/hset.go:61 +0x200
github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1.(*Data).HasIn(0xc052bca5a0, 0x1b0fe80, 0xc0332bbc80, 0xc05fdccea0, 0xc05fdcce80)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1/data_state.go:33 +0x56
github.com/sero-cash/go-sero/zero/txs/zstate/txstate.(*State).HasIn(0xc00bd73008, 0xc05fdccea0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/state.go:137 +0x9b
github.com/sero-cash/go-sero/zero/txs/verify.Verify_state1(0xc0131ea5a0, 0xc00bd72ff0, 0x11408e0, 0xc022871e68)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:85 +0x1638
github.com/sero-cash/go-sero/zero/txs/verify.Verify(0xc0131ea5a0, 0xc00bd72ff0, 0xc06e194c30, 0xc02af68ae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:44 +0x3c
github.com/sero-cash/go-sero/core.(*TxPool).validateTx(0xc000003380, 0xc06e194c30, 0x8cb8f6affef5e900, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:460 +0x108
github.com/sero-cash/go-sero/core.(*TxPool).add(0xc000003380, 0xc06e194c30, 0x0, 0xc02ae4e9a0, 0x1, 0x1)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:497 +0xd4
github.com/sero-cash/go-sero/core.(*TxPool).addTxsLocked(0xc000003380, 0xc04aa4f4a0, 0x1, 0x4, 0x0, 0xc02af69148, 0x2, 0x2)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:599 +0xc4
github.com/sero-cash/go-sero/core.(*TxPool).addTxs(0xc000003380, 0xc04aa4f4a0, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:589 +0xb6
github.com/sero-cash/go-sero/core.(*TxPool).AddRemotes(0xc000003380, 0xc04aa4f4a0, 0x1, 0x4, 0x7d9d00438cb46e70, 0xee30cafd57d, 0x2166b80)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:567 +0x172
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handleMsg(0xc000544300, 0xc0680c0480, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:623 +0x48a
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handle(0xc000544300, 0xc0680c0480, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:285 +0x6f2
github.com/sero-cash/go-sero/sero.NewProtocolManager.func1(0xc00837c540, 0x1b09100, 0xc01071c000, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:137 +0x1bf
github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols.func1(0xc01071c000, 0xc00837c540, 0x1b09100, 0xc01071c000)
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:353 +0x6d
created by github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:352 +0x202
ERROR[04-16|18:10:05.518] validateTx error :                       hash=0x99c9449d9d10f9c4dcbcefcefdd0446fd1e4f474a2bc92f88fc21980f5187608 recover="missing trie node 29545969bfecf5ada4ec131621f094c710
740454db5b29fcf955aad03217af36 (path 0603)"
goroutine 20632 [running]:
runtime/debug.Stack(0x1260b22, 0x13, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/sero-cash/go-sero/core.(*TxPool).validateTx.func1(0xc084b3cfa0, 0xc008e10ae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:445 +0x1ad
panic(0x112ec60, 0xc0da82ff40)
        /usr/local/go/src/runtime/panic.go:513 +0x1c7
github.com/sero-cash/go-sero/zero/utils.(*HSet).Has(0xc052bca5c8, 0x1b0fe80, 0xc0332bbc80, 0xc033bcbb20, 0xc008e0ffc8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/utils/hset.go:61 +0x200
github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1.(*Data).HasIn(0xc052bca5a0, 0x1b0fe80, 0xc0332bbc80, 0xc033bcbb20, 0xc033bcbb00)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1/data_state.go:33 +0x56
github.com/sero-cash/go-sero/zero/txs/zstate/txstate.(*State).HasIn(0xc00bd73008, 0xc033bcbb20, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/state.go:137 +0x9b
github.com/sero-cash/go-sero/zero/txs/verify.Verify_state1(0xc021bd7680, 0xc00bd72ff0, 0x11408e0, 0xc0556f0330)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:184 +0x8a9
github.com/sero-cash/go-sero/zero/txs/verify.Verify(0xc021bd7680, 0xc00bd72ff0, 0xc084b3cfa0, 0xc008e10ae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:44 +0x3c
github.com/sero-cash/go-sero/core.(*TxPool).validateTx(0xc000003380, 0xc084b3cfa0, 0x6f44d0fdceefbc00, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:460 +0x108
github.com/sero-cash/go-sero/core.(*TxPool).add(0xc000003380, 0xc084b3cfa0, 0x0, 0xc064286260, 0x1, 0x1)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:497 +0xd4
github.com/sero-cash/go-sero/core.(*TxPool).addTxsLocked(0xc000003380, 0xc03e369700, 0x1, 0x4, 0x0, 0xc008e11148, 0x2, 0x2)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:599 +0xc4
github.com/sero-cash/go-sero/core.(*TxPool).addTxs(0xc000003380, 0xc03e369700, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:589 +0xb6
github.com/sero-cash/go-sero/core.(*TxPool).AddRemotes(0xc000003380, 0xc03e369700, 0x1, 0x4, 0x87618f58019c28f, 0xee3254e12ed, 0x2166b80)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:567 +0x172
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handleMsg(0xc000544300, 0xc0680c0480, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:623 +0x48a
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handle(0xc000544300, 0xc0680c0480, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:285 +0x6f2
github.com/sero-cash/go-sero/sero.NewProtocolManager.func1(0xc00837c540, 0x1b09100, 0xc01071c000, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:137 +0x1bf
github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols.func1(0xc01071c000, 0xc00837c540, 0x1b09100, 0xc01071c000)
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:353 +0x6d
created by github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:352 +0x202
ERROR[04-16|18:10:07.343] validateTx error :                       hash=0x99c9449d9d10f9c4dcbcefcefdd0446fd1e4f474a2bc92f88fc21980f5187608 recover="missing trie node 29545969bfecf5ada4ec131621f094c710
740454db5b29fcf955aad03217af36 (path 0603)"
goroutine 130551 [running]:
runtime/debug.Stack(0x1260b22, 0x13, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/sero-cash/go-sero/core.(*TxPool).validateTx.func1(0xc05b19aaa0, 0xc002608ae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:445 +0x1ad
panic(0x112ec60, 0xc00489a6c0)
        /usr/local/go/src/runtime/panic.go:513 +0x1c7
github.com/sero-cash/go-sero/zero/utils.(*HSet).Has(0xc052bca5c8, 0x1b0fe80, 0xc0332bbc80, 0xc04354fe80, 0xc002607fc8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/utils/hset.go:61 +0x200
github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1.(*Data).HasIn(0xc052bca5a0, 0x1b0fe80, 0xc0332bbc80, 0xc04354fe80, 0xc04354fe60)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/data_v1/data_state.go:33 +0x56
github.com/sero-cash/go-sero/zero/txs/zstate/txstate.(*State).HasIn(0xc00bd73008, 0xc04354fe80, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/zstate/txstate/state.go:137 +0x9b
github.com/sero-cash/go-sero/zero/txs/verify.Verify_state1(0xc004aa8f00, 0xc00bd72ff0, 0x11408e0, 0xc057f4c940)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:184 +0x8a9
github.com/sero-cash/go-sero/zero/txs/verify.Verify(0xc004aa8f00, 0xc00bd72ff0, 0xc05b19aaa0, 0xc002608ae8)
        /ext-go/1/src/github.com/sero-cash/go-sero/zero/txs/verify/txs_verify.go:44 +0x3c
github.com/sero-cash/go-sero/core.(*TxPool).validateTx(0xc000003380, 0xc05b19aaa0, 0x6f44d0fdceefbc00, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:460 +0x108
github.com/sero-cash/go-sero/core.(*TxPool).add(0xc000003380, 0xc05b19aaa0, 0x0, 0xc03358cd50, 0x1, 0x1)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:497 +0xd4
github.com/sero-cash/go-sero/core.(*TxPool).addTxsLocked(0xc000003380, 0xc04f4f23c0, 0x1, 0x4, 0x0, 0xc002609148, 0x2, 0x2)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:599 +0xc4
github.com/sero-cash/go-sero/core.(*TxPool).addTxs(0xc000003380, 0xc04f4f23c0, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:589 +0xb6
github.com/sero-cash/go-sero/core.(*TxPool).AddRemotes(0xc000003380, 0xc04f4f23c0, 0x1, 0x4, 0x87618f58019c28f, 0xee39216f4fd, 0x2166b80)
        /ext-go/1/src/github.com/sero-cash/go-sero/core/tx_pool.go:567 +0x172
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handleMsg(0xc000544300, 0xc00009e000, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:623 +0x48a
github.com/sero-cash/go-sero/sero.(*ProtocolManager).handle(0xc000544300, 0xc00009e000, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:285 +0x6f2
github.com/sero-cash/go-sero/sero.NewProtocolManager.func1(0xc05ba0e540, 0x1b09100, 0xc0624904d0, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/sero/handler.go:137 +0x1bf
github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols.func1(0xc0624904d0, 0xc05ba0e540, 0x1b09100, 0xc0624904d0)
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:353 +0x6d
created by github.com/sero-cash/go-sero/p2p.(*Peer).startProtocols
        /ext-go/1/src/github.com/sero-cash/go-sero/p2p/peer.go:352 +0x202`

**Comment by gordon-sero** [comment]
@Bambarello thank you

This bug now had been fixed in v1.0.0-rc2

**Comment by Bambarello** [comment]
no more relevant
